config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users do 
  	collection do 
       get 'sign_in'
       post 'signup'
       delete 'logout'
  	end
  end
  root to: "users#sign_in" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
     if user.admin?
        can :manage, :all
       else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>", small: "200x200>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
	belongs_to :user
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :images
end

app/models/rolename.rb
class Rolename < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
	validates :password , presence: true
	validates :confirm_password , presence: true
	validates :mobile, presence: true, numericality: true
  has_one :image
  has_and_belongs_to_many :roles
  accepts_nested_attributes_for :image
    before_save :encrypt_password
    
    before_validation :verify_password
def  admin?
  self.roles.pluck(:name).include?("admin")
end
def check_name
  if name.blank?
    self.name="unknown"
  end 
end

   def encrypt_password
   	unless password.nil?
       self.password = Digest::MD5.hexdigest(password)
       self.confirm_password = Digest::MD5.hexdigest(confirm_password)
    end
end
    def verify_password
    	unless password.nil?
     	if password != confirm_password
           errors.add(:base, "password & confirm_password are not equal!" )
    	end
    end
    end
    def self.authenticate(email, password)
       if @user = User.where(email: email, password: Digest::MD5.hexdigest(password)).last
           @user
        else
           nil
         end
     end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
     protect_from_forgery with: :exception

   before_action :authenticate_user
     def authenticate_user
      if session[:user_id].blank?
          redirect_to sign_in_users_path
       end
     end
     #def current_user
     	#if session[:user_id]
     	#	User.find session[:user_id]
     	#else
     	#	nil
       # end
     #end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #skip_before_action :authenticate_user, only: [:index]
  def index
  	@product = Product.all
  end

  def new
  	@product = Product.new
  end
  def create
  	 image_attributes = product_params[:image]["photo"]
     product_params.delete(:image)
     @product = Product.new(product_params)
     if @product.save
        image_attributes.each do |each_image|
          image = Image.new(photo: each_image, product: @product)
          image.save(validate: false)
        end
        redirect_to products_path
        else
         render :new
     end
  end
  def edit
  end

  def show
  end

  private
  def product_params
  	params.require(:product).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 skip_before_action :authenticate_user, only: [:sign_in, :signup, :new, :create]
  def index
  	@users=User.all
  end

  def new
  	@user=User.new
      @user.build_image
  end
  def create
  	@user=User.new(user_params)
  	if @user.save
  	redirect_to users_path
  	else
  		render :new
  	end
  end
  def edit
      @user = User.find params[:id]
  end
def update
    @user = User.find params[:id]
    if @user.update(user_params)
       redirect_to users_path
       else
       render :edit 
    end
  end 
  def show
    @user = User.find params[:id]
  end
def destroy 
     @user = User.find params[:id]
     @user.destroy
     redirect_to users_path
  end
  def signup
      @user = User.authenticate(params[:email], params[:password])
      if @user
          session[:user_id] = @user.id
          redirect_to products_path
        else
          redirect_to sign_in_users_path
      end
  end
  def logout
    session[:user_id] = nil
    redirect_to sign_in_users_path
  end
private
def user_params
	params.require(:user).permit!
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roja1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<%=link_to "add product",new_product_path%>
<table class="table table-striped">
	<tr>
	    <th>Image</th>
	    <th>Name</th>
		<th>Brand</th>
		<th>Price</th>
		<th>Size</th>
		</tr>
<% @product.each do | i | %>
<tr>
   
  	  <td>
	  <% unless i.images.blank? %>
	    <% i.images.each do | image |%>
          <%= image_tag image.photo(:thumb)%>
	    <%end%>
	  <%end%>

   
  
  

	</td>
	  <td><%= i.name %></td>
      <td><%= i.brand %></td>
      <td><%= i.price %></td>
      <td><%= i.size %></td>
    </tr>
<%end%>
</table>

app/views/products/new.html.erb
<%=form_for @product do |f|%>
<table  class="table table-striped">
  
  
  <tr>
  <td><%= f.label :name%></td>
  <td><%= f.text_field :name%></td>
  </tr>
  <tr>
  <td><%= f.label :brand%></td>
  <td><%= f.text_field :brand%></td>
  </tr>
  <tr>
  <td><%= f.label :price%></td>
  <td><%= f.text_field :price%></td>
  </tr>
  <tr>
  <td><%= f.label :size%></td>
  <td><%= f.select :size, %w(S M L XS XM XL )%></td>
  </tr>
  <%= f.fields_for :image do | image |%>
     <tr>
     <td><%= image.label :photo%></td>
     <td><%= image.file_field :photo,multiple: true%></td>
     
     </tr>
     <%end%>
    <tr>
  <td><%= f.submit "Add Product"%></td>
  </tr>
</table>
<%end%>

<%= link_to "<<back", products_path%>

app/views/users/edit.html.erb
<%= form_for @user do |f|%>
<table>
  <tr>
  <td><%= f.label :name%></td>
  <td><%= f.text_field :name%></td>
  </tr>
  <tr>
  <td><%= f.label :email%></td>
  <td><%= f.email_field :email%></td>
  </tr>
  <tr>
  <td><%= f.label :password%></td>
  <td><%= f.password_field :password%></td>
  </tr>
  <tr>
  <td><%= f.label :confirm_password%></td>
  <td><%= f.password_field :confirm_password%></td>
  </tr>
  <tr>
  <td><%= f.label :mobile%></td>
  <td><%= f.text_field :mobile%></td>
  </tr>
  <tr>
  <td><%= f.label :gender%></td>
  <td><%= f.select :gender,%w(female male)%>
  </tr>
    <tr>
  <td><%= f.submit "Save"%></td>
  </tr>
</table>
<%end%>

<%= link_to "<<back", users_path%>

app/views/users/index.html.erb
<!--%= @users.inspect %-->

 <table class="table table-bordered">
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Password</th>
		<th>confirm_password</th>
		<th>Gender</th>
		<th>Mobile</th>
		</tr>
<% @users.each do | i | %>
	<tr>  
      <td><%= i.name %></td>
      <td><%= i.email %></td>
      <td><%= i.password %></td>
      <td><%= i.confirm_password %></td>
      <td><%= i.gender%></td>
      <td><%= i.mobile %></td>
      <td><%= link_to "Show", user_path(i)%></td>
      <td><%= link_to "Edit", edit_user_path(i)%></td>
      <td><%= link_to "Delete", i, method: :delete, data: {confirm: "Are you sure!"}%></td>
      
<%end%>
</table>

<%= link_to "Add New User", new_user_path%>

app/views/users/new.html.erb
<%= form_for (User.new) do |f| %>
<table>
  <tr>
  <td><%= f.label :name%></td>
  <td><%= f.text_field :name%></td>
  </tr>
  <tr>
  <td><%= f.label :email%></td>
  <td><%= f.email_field :email%></td>
  </tr>
  <tr>
  <td><%= f.label :password%></td>
  <td><%= f.password_field :password%></td>
  </tr>
  <tr>
  <td><%= f.label :confirm_password%></td>
  <td><%= f.password_field :confirm_password%></td>
  </tr>
  <tr>
  <td><%= f.label :gender%></td>
  <td><%= f.select :gender,%w(female male)%></td>
  </tr>
  <tr>
  <td><%= f.label :mobile%></td>
  <td><%= f.text_field :mobile%></td>
  </tr>
  <tr>
  <td><%= f.submit "save"%></td>
  </tr>
  </table>
  <%end%>

app/views/users/show.html.erb
table>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Password</th>
		<th>Confirm_password</th>
		<th>Mobile</th>
		<th>Gender</th>
		</tr>

	<tr>  
      <td><%= @user.name%></td>
      <td><%= @user.email%></td>
      <td><%= @user.password %></td>
      <td><%= @user. confirm_password%></td>
      <td><%= @user.mobile%></td>
      <td><%= @user.gender%></td>
      <td><%= link_to "Show", user_path(@user)%>
      <td><%= link_to "Edit", edit_user_path(@user)%></td>
      </tr>

</table>

<%= link_to "<<back", users_path%>

app/views/users/sign_in.html.erb
<%= form_tag action: :signup, method: :post do%>
<table  class="table table-striped">
  <tr>
  <td><%= label_tag :email%></td>
  <td><%= email_field_tag :email%></td>
  </tr>
  <tr>
  <td><%= label_tag :password%></td>
  <td><%= password_field_tag :password%></td>
  </tr>
   <tr>
  <td><%= submit_tag "SignIn"%></td>
  <td><%= link_to "SignUp", new_user_path%></td>
  </tr>
</table>
<%end%>